/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ClienteDAO;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author EDUARDO
 */
public class JFCliente extends javax.swing.JFrame {

    protected ClienteDAO controle = new ClienteDAO();
    protected boolean selec = false;

    public JFCliente() {
        initComponents();
        controle.conectar();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBackground = new javax.swing.JPanel();
        JPTitulo = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLNomeAba = new javax.swing.JLabel();
        jPBarrinhaAba = new javax.swing.JPanel();
        jLTituloCad = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jLSobrenome = new javax.swing.JLabel();
        jTSobrenome = new javax.swing.JTextField();
        jLCPF = new javax.swing.JLabel();
        jTCPF = new javax.swing.JTextField();
        jBEnviar = new javax.swing.JButton();
        jTEndereco = new javax.swing.JTextField();
        jLNomeAba7 = new javax.swing.JLabel();
        jTBairro = new javax.swing.JTextField();
        jLNomeAba6 = new javax.swing.JLabel();
        jTCidade = new javax.swing.JTextField();
        jLCidade = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JPBarrinha = new javax.swing.JPanel();
        jBLivros = new javax.swing.JButton();
        jBAluguel = new javax.swing.JButton();
        jLFechar = new javax.swing.JLabel();
        jCEstados = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(528, 529));

        JBackground.setBackground(new java.awt.Color(245, 244, 244));
        JBackground.setPreferredSize(new java.awt.Dimension(528, 529));
        JBackground.setRequestFocusEnabled(false);

        JPTitulo.setBackground(new java.awt.Color(202, 228, 219));

        jLNomeAba.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLNomeAba.setText("CLIENTES");

        jPBarrinhaAba.setBackground(new java.awt.Color(0, 0, 0));
        jPBarrinhaAba.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPBarrinhaAbaLayout = new javax.swing.GroupLayout(jPBarrinhaAba);
        jPBarrinhaAba.setLayout(jPBarrinhaAbaLayout);
        jPBarrinhaAbaLayout.setHorizontalGroup(
            jPBarrinhaAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPBarrinhaAbaLayout.setVerticalGroup(
            jPBarrinhaAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(jLNomeAba, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPBarrinhaAba, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPBarrinhaAba, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jLNomeAba, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNomeAba)
                .addGap(3, 3, 3)
                .addComponent(jPBarrinhaAba, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout JPTituloLayout = new javax.swing.GroupLayout(JPTitulo);
        JPTitulo.setLayout(JPTituloLayout);
        JPTituloLayout.setHorizontalGroup(
            JPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        JPTituloLayout.setVerticalGroup(
            JPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPTituloLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jLTituloCad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLTituloCad.setText("CADASTRO");

        jLNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNome.setText("Nome:");

        jTNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLSobrenome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLSobrenome.setText("Sobrenome:");

        jTSobrenome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLCPF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCPF.setText("Cpf:");

        jTCPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jBEnviar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBEnviar.setText("Enviar");
        jBEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBEnviarMouseClicked(evt);
            }
        });

        jTEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEnderecoActionPerformed(evt);
            }
        });

        jLNomeAba7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNomeAba7.setText("Endereço");

        jTBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLNomeAba6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNomeAba6.setText("Bairro:");

        jTCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCidade.setText("Cidade:");

        jLEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLEstado.setText("Estado:");

        jPanel.setBackground(new java.awt.Color(0, 48, 63));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROGRAMA LIVRARIA");

        JPBarrinha.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout JPBarrinhaLayout = new javax.swing.GroupLayout(JPBarrinha);
        JPBarrinha.setLayout(JPBarrinhaLayout);
        JPBarrinhaLayout.setHorizontalGroup(
            JPBarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        JPBarrinhaLayout.setVerticalGroup(
            JPBarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jBLivros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBLivros.setText("LIVROS");
        jBLivros.setPreferredSize(new java.awt.Dimension(87, 23));
        jBLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBLivrosMouseClicked(evt);
            }
        });

        jBAluguel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBAluguel.setText("ALUGUEL");
        jBAluguel.setPreferredSize(new java.awt.Dimension(87, 23));
        jBAluguel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAluguelMouseClicked(evt);
            }
        });
        jBAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAluguelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(JPBarrinha, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(JPBarrinha, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLFechar.setBackground(new java.awt.Color(245, 244, 244));
        jLFechar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLFechar.setText("X");
        jLFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLFecharMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLFecharMouseExited(evt);
            }
        });

        jCEstados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jCEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCEstadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JBackgroundLayout = new javax.swing.GroupLayout(JBackground);
        JBackground.setLayout(JBackgroundLayout);
        JBackgroundLayout.setHorizontalGroup(
            JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))
                    .addGroup(JBackgroundLayout.createSequentialGroup()
                        .addGroup(JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JBackgroundLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLNome, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLTituloCad, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTNome)
                                        .addComponent(jLSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTSobrenome)
                                        .addComponent(jLCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jBEnviar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jTBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jTCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addGroup(JBackgroundLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLNomeAba6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLNomeAba7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jCEstados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(JBackgroundLayout.createSequentialGroup()
                                .addGap(312, 312, 312)
                                .addComponent(jLFechar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JBackgroundLayout.setVerticalGroup(
            JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JBackgroundLayout.createSequentialGroup()
                .addComponent(jLFechar)
                .addGap(3, 3, 3)
                .addComponent(JPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTituloCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JBackgroundLayout.createSequentialGroup()
                        .addComponent(jLNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JBackgroundLayout.createSequentialGroup()
                        .addComponent(jLEstado)
                        .addGap(28, 28, 28)))
                .addGroup(JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBackgroundLayout.createSequentialGroup()
                        .addComponent(jLSobrenome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JBackgroundLayout.createSequentialGroup()
                        .addComponent(jLCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JBackgroundLayout.createSequentialGroup()
                        .addComponent(jLNomeAba6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLNomeAba7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBEnviar)))
                    .addGroup(JBackgroundLayout.createSequentialGroup()
                        .addComponent(jLCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEnviarMouseClicked
        enviarCliente();
        if(controle.inserir()){
            limparCampos();
        }
    }//GEN-LAST:event_jBEnviarMouseClicked

    private void jTEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEnderecoActionPerformed

    private void jBLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLivrosMouseClicked
        controle.desconectar();
        JFLivro jfl = new JFLivro();
        jfl.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBLivrosMouseClicked

    private void jLFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFecharMouseClicked
        controle.desconectar();
        System.exit(0);
    }//GEN-LAST:event_jLFecharMouseClicked

    private void jLFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFecharMouseEntered
        jLFechar.setForeground(Color.red);
    }//GEN-LAST:event_jLFecharMouseEntered

    private void jLFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFecharMouseExited
        jLFechar.setForeground(UIManager.getColor("control"));
    }//GEN-LAST:event_jLFecharMouseExited

    private void jBAluguelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAluguelMouseClicked
        controle.desconectar();
        JFAluguel jfa = new JFAluguel();
        jfa.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBAluguelMouseClicked

    private void jBAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAluguelActionPerformed

    private void jCEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCEstadosActionPerformed

    public void limparCampos(){
        jTBairro.setText("");
        jTCPF.setText("");
        jTCidade.setText("");
        jTEndereco.setText("");
        jCEstados.setSelectedIndex(0);
        jTNome.setText("");
        jTSobrenome.setText("");
    }
      
    public void enviarCliente(){
        controle.getCliente().setNome(jTNome.getText());
        controle.getCliente().setSobrenome(jTSobrenome.getText());
        controle.getCliente().setEstado(jCEstados.getSelectedItem().toString());
        controle.getCliente().setEndereco(jTEndereco.getText());
        controle.getCliente().setCidade(jTCidade.getText());
        controle.getCliente().setCPF(jTCPF.getText());
        controle.getCliente().setBairro(jTBairro.getText());
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCliente().setVisible(true);
            }
        });
    }



    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JBackground;
    private javax.swing.JPanel JPBarrinha;
    private javax.swing.JPanel JPTitulo;
    private javax.swing.JButton jBAluguel;
    private javax.swing.JButton jBEnviar;
    private javax.swing.JButton jBLivros;
    private javax.swing.JComboBox<String> jCEstados;
    private javax.swing.JLabel jLCPF;
    private javax.swing.JLabel jLCidade;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLFechar;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLNomeAba;
    private javax.swing.JLabel jLNomeAba6;
    private javax.swing.JLabel jLNomeAba7;
    private javax.swing.JLabel jLSobrenome;
    private javax.swing.JLabel jLTituloCad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPBarrinhaAba;
    private javax.swing.JPanel jPanel;
    private javax.swing.JTextField jTBairro;
    private javax.swing.JTextField jTCPF;
    private javax.swing.JTextField jTCidade;
    private javax.swing.JTextField jTEndereco;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTSobrenome;
    // End of variables declaration//GEN-END:variables
}
